pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'paulke1039/my-node-app'
  dockerId: 'paulke1039'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
- script: docker login -u $(dockerId) -p $(pswd)
- script: docker push $(imageName)
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    contents: '**/deployment.yaml' 
    targetFolder: $(Build.ArtifactStagingDirectory)
    overWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
  displayName: 'docker build'
