---
kind: Service
apiVersion: v1
metadata:
  name: my-node-app-service 
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 4000
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-node-app-deployment 
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app-container 
          image: rapiddevpro/my-node-app
          ports:
            - containerPort: 4000
